# Build website
[build]
  command = ""
  publish = ""

[[redirects]]
  from = "/"
  to = "https://www.pixelastic.com/talks/"
  force = true
  status = 301


[[redirects]]
  from = "/slides/algolia-community-reddinx/*"
  to = "https://talks-reddinx.netlify.app/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
