#!/usr/bin/env bash

rsync \
      --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
      --verbose \
      --archive \
      --update \
      --delete \
      --filter 'protect /slides/' \
      --prune-empty-dirs \
      --copy-links \
      --compress \
      ./source/ \
      pixelastic:/var/www/pixelastic.com/talks.pixelastic.com/
